def main():
    var1=input('Enter 1st Variable: ')
    var2=input('Enter 2nd Variable: ')
    var3=input('Enter 3rd Varibale: ')
    print(var1)
    print(var2)
    print(var3)
    print(var1.isdecimal())
    print(var1.isnumeric())
    print(var2.isdecimal())
    print(var2.isnumeric())
    print(var3.isdecimal())
    print(var3.isnumeric())
print('check if a string can be converted to a number?')
main()